name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repo
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Log ind på Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Byg Docker image
    - name: Build Docker image
      run: docker build -t fipo0001/legobackendapp:latest .

    # 4. Push Docker image til Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push fipo0001/legobackendapp:latest

    # 5. Deploy til Azure
    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: lego-assistant-backend
        slot-name: production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
