name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build and test with Maven
      - name: Build and test with Maven
        run: mvn clean verify

      # 4. Upload JAR artifact (med retention-days)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: target/*.jar
          retention-days: 1

      # 4. Log ind på Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 5. Byg Docker image
      - name: Build Docker image
        run: docker build -t fipo0001/legobackendapp:latest .

      # 6. Push Docker image til Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push fipo0001/legobackendapp:latest

      # 7. Deploy til Azure
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: lego-assistant-backend
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
